apiVersion: batch/v1
kind: Job
metadata:
  name: benchmark-job
spec:
  template:
    spec:
      containers:
      - name: benchmark
        image: your-registry/benchmark:latest  # Replace with your actual image
        env:
        - name: MODEL
          value: "meta-llama/Llama-3.1-8B-Instruct"
        - name: BASE_URL
          value: "http://vllm-service:8000"  # Replace with your actual service name
        - name: SAVE_FILE_KEY
          value: "benchmark_results"
        - name: SCENARIOS
          value: "all"  # Options: all, sharegpt, short-input, long-input
        - name: QPS_VALUES
          value: "1.34 2.0 3.0"  # Space-separated list of QPS values
        volumeMounts:
        - name: results-volume
          mountPath: /app/results
      volumes:
      - name: results-volume
        persistentVolumeClaim:
          claimName: benchmark-results-pvc  # Replace with your actual PVC
      restartPolicy: Never
  backoffLimit: 0  # Don't retry on failure 